const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("542327412189560832")
setInterval(function() {
channel.send(`spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcradit`);
}, 30)
})

client.login(process.env.BOT_TOKEN);
